arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j2s6s300_joint_1
    - j2s6s300_joint_2
    - j2s6s300_joint_3
    - j2s6s300_joint_4
    - j2s6s300_joint_5
    - j2s6s300_joint_6
  gains:
    j2s6s300_joint_1:
      p: 220
      d: 1
      i: 4
      i_clamp: 1
    j2s6s300_joint_2:
      p: 8000
      d: 20
      i: 85
      i_clamp: 1
    j2s6s300_joint_3:
      p: 8000
      d: 20
      i: 85
      i_clamp: 1
    j2s6s300_joint_4:
      p: 100
      d: 0.1
      i: 1
      i_clamp: 1
    j2s6s300_joint_5:
      p: 400
      d: 1
      i: 4
      i_clamp: 1
    j2s6s300_joint_6:
      p: 100
      d: 0.1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j2s6s300_joint_finger_1
    - j2s6s300_joint_finger_tip_1
    - j2s6s300_joint_finger_2
    - j2s6s300_joint_finger_tip_2
    - j2s6s300_joint_finger_3
    - j2s6s300_joint_finger_tip_3
  gains:
    j2s6s300_joint_finger_1:
      p: 1
      d: 0
      i: 2
      i_clamp: 1
    j2s6s300_joint_finger_tip_1:
      p: 0.1
      d: 0
      i: 1
      i_clamp: 1
    j2s6s300_joint_finger_2:
      p: 1
      d: 0
      i: 2
      i_clamp: 1
    j2s6s300_joint_finger_tip_2:
      p: 0.1
      d: 0
      i: 1
      i_clamp: 1
    j2s6s300_joint_finger_3:
      p: 1
      d: 0
      i: 2
      i_clamp: 1
    j2s6s300_joint_finger_tip_3:
      p: 0.1
      d: 0
      i: 1
      i_clamp: 1