controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j2s6s300_joint_1
      - j2s6s300_joint_2
      - j2s6s300_joint_3
      - j2s6s300_joint_4
      - j2s6s300_joint_5
      - j2s6s300_joint_6
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j2s6s300_joint_finger_1
      - j2s6s300_joint_finger_tip_1
      - j2s6s300_joint_finger_2
      - j2s6s300_joint_finger_tip_2
      - j2s6s300_joint_finger_3
      - j2s6s300_joint_finger_tip_3